Milestone: First Capstone Project
willy836/First-Capstone-Project-Concert-Page pull request #1
Opened 2022-11-24 17:34 UTC by willy836

**Concert Website Milestone: First Capstone Project**
In this milestone, I:

- Built a concert website with personalized content based on an online website for a conference

2022-11-24 19:31 UTC, Olamarx requested changes
Hi @willy836, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media2.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

## Highlights
- All linters passed 👍🏼 
- Dynamic rendering ✔️ 
- Home and About pages ✅

## Required Changes ♻️
_Check the comments under the review._
- [ ] You have probably forgotten to record the video. Kindly do this so that you will meet all the requirements.
- [ ] I will encourage you to use the latest readme file which is detailed and of the latest. You can find it [here](https://github.com/microverseinc/readme-template)
- [ ] On a general note, the font sizes are too big. I will recommend you stick to the Behance design.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-24 19:31 UTC, Olamarx commented on README.md
> +[Creative Commons Online Website for a Conference Link](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)
- [ ] Kindly give credit by stating the name of Cindy Chin. You should understand what I am saying because if credit is been given but not stating the person's name, then it is not given to anybody.

2022-11-24 19:31 UTC, Olamarx commented on index.html
> +                    </div>
- [ ] This hamburger on the Home page mobile version should be on the left as it is on Behance
![image](https://user-images.githubusercontent.com/86200356/203847743-109d7e60-e1ed-43e8-b3b1-c31c00da832c.png)

2022-11-24 19:31 UTC, Olamarx commented on index.html
> +        </footer>
- [ ] The mobile version should also display flex as it is on Behance
### Your design
![image](https://user-images.githubusercontent.com/86200356/203849198-a46d9a57-3f67-48cf-91a0-dfe116ce7b3c.png)

### Behance
![image](https://user-images.githubusercontent.com/86200356/203849338-45431e70-cdf9-424a-91b9-0eb88eb6f465.png)

2022-11-24 19:31 UTC, Olamarx commented on index.html
> +                </article>
- [ ] Kindly align the content of this article to align on the same lines

### Your Design
![image](https://user-images.githubusercontent.com/86200356/203850598-b96e3304-e02b-456f-968b-4c30837f28e7.png)

### Behance
![image](https://user-images.githubusercontent.com/86200356/203850654-4f587cd5-47ac-49ea-a19d-afc0b7b86de7.png)

2022-11-24 19:31 UTC, Olamarx commented on homepage.html
> +        </h1>
- [ ] This content is too large and many of the other contents, kindly stick to the font size of the Behance

### Your design
![image](https://user-images.githubusercontent.com/86200356/203852742-b887b092-d45d-4a88-ab12-6599016e3231.png)

### Behance
![image](https://user-images.githubusercontent.com/86200356/203852529-90c746df-0faf-4ff7-a614-67d1e0c22d7d.png)

2022-11-25 12:23 UTC, emmiiorji approved these changes
Hi @willy836, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congratulations-2805](https://user-images.githubusercontent.com/20554583/203687220-ff1a910f-f657-4970-a6e8-0c6fb31dbc7f.gif)

## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- You have implemented requested changes


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 13:00 UTC, merged